[package]
name = "reset_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
ReSet-Lib = "0.2.3"
dbus = "0.9.7"
dbus-crossroads = "0.5.2"
dbus-tokio = "0.7.6"
tokio = { version = "1.33.0", features = ["rt", "time", "net", "macros", "rt-multi-thread", "sync"] }
pulse = { version = "2.0", package = "libpulse-binding" }
